# Global
global:
  postgresql:
    password: ""
    database: ""


environment: prod
namespace: api  
container:
  name: restaurant-api
  port: 8080
  image:
    repository: 'github.com/amosehiguese/restaurant-api'
    tag: '1.0.0'
request:
  cpu: 200m
  memory: 180Mi
limit:
  cpu: 300m
  memory: 300Mi
replicas: 3

# Redis Values
# redis:
#   name: redis
#   replicas: 3
#   labels: 
#     app: redis
#   port: 6379
#   image:
#     repository: redis
#     tag: 7.2.3-alpine
